# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a050590a15bc78b873f45337b57d00a9c7dd6feb8b9e82ec7c668b286c08403e52c0f1567b8a27b9c2de7495876918264dfebc4b2221232c924cea21cd60edb

test:
  secret_key_base: 6abbcccaadc248f081a6d804901cce13e042f45df92919c99d4d19f221ac09dc77adf1470cc97436df079e40d594b7247167772eafefffa0242146cc62c75eaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
